In [6]:
#Carregando os dados
import pandas as pd

In [4]:
tabela=pd.read_csv('C:/Users/paulo/OneDrive/Área de Trabalho/Python Pandas/Kaggle/wine_dataset.csv')
tabela.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [13]:
#Trocando os valores do vinho por 0 e 1
tabela['style'] = tabela['style'].replace('red',0)
tabela['style'] = tabela['style'].replace('white',1)

In [16]:
#Separando as variáveis
y = tabela['style']
x = tabela.drop('style', axis = 1)

In [19]:
#Criando o Treino e Teste
from sklearn.model_selection import train_test_split
x_treino, x_test, y_treino, y_test = train_test_split(x,y, test_size = 0.3)

In [28]:
#Criando o modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)
#Imprimindo o resultado
resultado = modelo.score(x_test, y_test)
print('Probabilidade: ',resultado)

Probabilidade:  0.9969230769230769

In [29]:
y_test[500:505]

2876    1
5219    1
5228    1
2981    1
1457    0
Name: style, dtype: int64

In [30]:
x_test[500:505]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2876,7.6,0.31,0.29,10.5,0.040,21.0,145.0,0.99660,3.04,0.35,9.4,5
5219,6.3,0.20,0.26,4.7,0.040,108.0,168.0,0.99278,3.07,0.75,10.7,7
5228,6.4,0.36,0.20,5.7,0.118,61.0,172.0,0.99460,3.24,0.43,9.5,6
2981,6.6,0.56,0.16,3.1,0.045,28.0,92.0,0.99400,3.12,0.35,9.1,6
1457,7.6,0.49,0.33,1.9,0.074,27.0,85.0,0.99706,3.41,0.58,9.0,5

In [33]:
previsao= modelo.predict(x_test[500:505])
print(previsao)# A máquina aprendeu a visualizar o test X e sabe se ela é vinho Branco ou Vermelho.

[1 1 1 1 0]